name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-07-31"

[vars]
UUID = "5999603a-00d7-482f-b123-f7272487200f"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
# UUID = "5999603a-00d7-482f-b123-f7272487200f, 63eee7fc-4ff1-4efc-a049-3923e0e0bcbf"